theme = "monokai"

[editor]
true-color = true
line-number = "relative"
idle-timeout = 100
cursorline = true
color-modes = true
# mouse = false


[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[keys.normal]
"#" = ["select_all",":pipe goimports",":w"]

[keys.insert]
k = { j = "normal_mode" }

[editor.file-picker]
hidden = false
git-ignore = true

[editor.whitespace.render]
tab = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
# tab = "→" #removed it for the new editor.indent-guides.render key
newline = "⏎"

[editor.indent-guides]
render = true


[editor.lsp]
display-messages = true


[editor.statusline]
left = ["mode", "spinner","file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
