[[language]]
name = "html"
auto-format = false

[[language]]
name = "python"
indent = { tab-width = 4 , unit = "\t" }

[language.config.pylsp.plugins.flake8]
enabled = false

[language.config.pylsp.plugins.autopep8]
enabled = false

[language.config.pylsp.plugins.pyflakes]
enabled = false

[language.config.pylsp.plugins.pycodestyle]
enabled = false

