[[language]]
name = "html"
auto-format = false

[[language]]
name = "python"
indent = { tab-width = 4 , unit = "\t" }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true


[language-server.pylsp]
config = { pylsp = { plugins = { flake8 = false, autopep8 = false, pyflakes = false, pycodestyle = false } } }

